# Generated by Django 5.2.4 on 2025-09-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='recent_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
